feat(codec): PPT-996 Add DNS and Message codec
spider-gazelle/matter pull request #2
Opened 2023-11-14 04:43 UTC by grkek

2023-11-15 22:34 UTC, stakach requested changes
@grkek could you please use bindata to define these structures, it makes the protocol much easier to reason with and reduces the possibility of errors

```crystal
require "bindata"

class MessageHeader < BinData
  endian little

  enum SessionType : UInt8
    Unicast = 0
    Group = 1
  end

  # Message flags
  bit_field do
    bits 4, :version
    bits 1, :message_flag_reserved
    bool source_node_set
    bool destination_group_id
    bool destination_node_id
  end

  uint16 :session_id

  # Security flags
  bit_field do
    bool privacy
    bool control
    bool message_extensions
    bits 3, :security_flag_reserved
    enum_bits 2, session_type : SessionType = SessionType::Unicast
  end

  uint32 :message_counter

  uint64 :source_node_id, onlyif: ->{ source_node_set }
  uint16 :destination_group_id, onlyif: ->{ destination_group_id }
  uint64 :destination_node_id, onlyif: ->{ destination_node_id }

  group :extensions, onlyif: ->{ message_extensions } do
    uint8 :ext_length, value: ->{ ext_payload.size.to_u8 }
    bytes :ext_payload, size: ->{ ext_length }
  end
end
```

2023-11-16 01:24 UTC, grkek commented
> @grkek could you please use bindata to define these structures, it makes the protocol much easier to reason with and reduces the possibility of errors
> 
> ```crystal
> require "bindata"
> 
> enum SessionType : UInt8
>   Unicast = 0
>   Group = 1
> end
> 
> class MessageHeader < BinData
>   endian little
> 
>   # Message flags
>   bit_field do
>     bits 4, :version
>     bits 1, :message_flag_reserved
>     bool source_node_set, value: ->{ source_node_id != 0 }
>     bool destination_group_id, value: ->{ destination_group_id != 0 }
>     bool destination_node_id, value: ->{ destination_node_id != 0 }
>   end
> 
>   uint16 :session_id
> 
>   # Security flags
>   bit_field do
>     bool privacy
>     bool control
>     bool message_extensions, value: ->{ extensions.ext_payload.size > 0 }
>     bits 3, :security_flag_reserved
>     enum_bits 2, session_type : SessionType = SessionType::Unicast
>   end
> 
>   uint32 :message_counter
> 
>   uint64 :source_node_id, onlyif: ->{ source_node_set }
>   uint16 :destination_group_id, onlyif: ->{ destination_group_id }
>   uint64 :destination_node_id, onlyif: ->{ destination_node_id }
> 
>   group :extensions, onlyif: ->{ message_extensions } do
>     uint8 :ext_length, value: ->{ ext_payload.size.to_u8 }
>     bytes :ext_payload, size: ->{ ext_length }
>   end
> end
> 
> # ...
> 
> header = io.read_bytes(MessageHeader)
> ```

I am following line by line to the implementation present in the official TypeScript repository, using BinData for this is interesting but debugging this and searching for the issues will be a lot of headache. IMO it is better to stick with line by line comparison and trust me I tried BinData and when something went wrong I got horribly lost that is why I opted to use direct no extra layer byte shenanigans.

2023-11-16 02:17 UTC, stakach commented
I am happy for you to get it working using line-by-line, write a spec that passes and then convert it BinData

```crystal
flags = (HEADER_VERSION << 4) | \
            (packet_header.destination_group_id.nil? ? 0 : PacketHeaderFlag::HasDestGroupId.value) | \
            (packet_header.destination_node_id.nil? ? 0 : PacketHeaderFlag::HasDestNodeId.value) | \
            (packet_header.source_node_id.nil? ? 0 : PacketHeaderFlag::HasSourceNodeId.value)

byte_format.encode(UInt8.new(flags), io)
```

vs 

```crystal
header.to_slice
# or
header.write io
```

that bindata took me 10min looking at the matter docs, I didn't look at your code or the typescript code to build it
but I would look at the typescript code for specs and logic

2023-11-16 06:12 UTC, stakach approved these changes

2023-11-22 15:36 UTC, merged