feat: PPT-1007 Add DER codec and refactor by extending modules with self
spider-gazelle/matter pull request #3
Opened 2023-12-05 05:45 UTC by grkek

- Added the DER codec
- Modified other codecs to extend self for ease of use

2023-12-05 11:04 UTC, stakach commented
You could support 64 bit integers using this algorithm from my implementation of this:
https://github.com/spider-gazelle/bindata/blob/master/src/bindata/asn1/data_types.cr

although not sure if required?

2023-12-06 10:43 UTC, grkek commented
> https://github.com/spider-gazelle/bindata/blob/master/src/bindata/asn1/data_types.cr

Not required, removed because of that

2023-12-07 05:49 UTC, stakach requested changes

2023-12-07 05:49 UTC, stakach commented on spec/matter_spec.cr
> +    crafted.hexstring.should eq original.hexstring
```crystal
encoded = "30 81 cb 30 71 ...".gsub(' ', "").hexbytes
crafted = Matter::Codec::DERCodec::Base.encode(packet)
crafted.hexstring.should eq encoded.hexstring
```

removes the need for the `original = Slice(UInt8).new(encoded.size) { |i| encoded[i] }` line

2023-12-07 10:46 UTC, grkek commented on spec/matter_spec.cr
> +    crafted.hexstring.should eq original.hexstring
Oh my, what a wonderful way to do that.

2023-12-11 06:06 UTC, merged